[env]
# Local development: relative path to Godot binary
# Container builds: GODOT4_BIN is set in container environment
GODOT4_BIN = { value = "../../tools/godot/Godot_v4.3-stable_win64.exe", relative = true }

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-pthread",
    "-C", "target-feature=+atomics",
    "-C", "link-args=-sSIDE_MODULE=2",
    "-C", "panic=abort",
    "-Zlink-native-libraries=no",
    "-Cllvm-args=-enable-emscripten-cxx-exceptions=0",
]
